### ISSUE TITLE
Add support for Wireguard

### ISSUE THREAD

**Issue by cmer** [deanishe/alfred-viscosity#15]
Wireguard is pretty much the best, fastest and most secure way to connect to a remote network. Would it be possible to add support for it? It'd be truly amazing to be able to manage all my VPNs in one place.

**Comment by deanishe** [comment]
> Would it be possible to add support for it?

No idea. The app isn't compatible with my Mac, unfortunately.

**Comment by cmer** [comment]
Curious... Why isn't compatible? It works on macOS just fine. It's actually on the app store.

On Wed, Aug 14, 2019 at 5:16 AM, Dean Jackson <notifications@github.com> wrote:
Would it be possible to add support for it?

No idea. The app isn't compatible with my Mac.

**Comment by deanishe** [comment]
Because my Mac doesn’t support Mavericks.

**Comment by deanishe** [comment]
I looked at the WireGuard app on another Mac. It doesn't support AppleScript, so there's no way for the workflow to control the app.
