### ISSUE TITLE
Application "Tunnelblick" is not installed

### ISSUE THREAD

**Issue by DieterHolvoet** [deanishe/alfred-viscosity#17]
Lately I've been unable to use this workflow. It was working fine before, but now everytime I try to run it I get the error _Application "Tunnelblick" is not installed_.

*   Tunnelblick 3.8.2a (build 5481)
*   Alfred 4.0.5 \[1118\]

**Comment by deanishe** [comment]
That's not much information to work with…

What does Alfred's debugger say? Where is the application Tunnelblick installed? What version of macOS are you using? Can Alfred/Spotlight find Tunnelblick?

**Comment by DieterHolvoet** [comment]
### What does Alfred's debugger say?

```
[18:31:36.354] Logging Started...
[18:31:40.646] VPN Manager[Script Filter] Queuing argument ''
[18:31:40.828] VPN Manager[Script Filter] Script with argv '' finished
[18:31:40.831] STDERR: VPN Manager[Script Filter] .
18:31:40 workflow.py:2061 DEBUG    ---------- VPN Manager (3.2.0) ----------
18:31:40 workflow.py:1468 DEBUG    reading settings from /Users/dieter/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.vpn.manager/settings.json
18:31:40 workflow.py:2343 DEBUG    update check not due
18:31:40 vpn.py:515 DEBUG    args : {'--all': False,
 '--help': False,
 '<name>': None,
 '<query>': u'',
 'app': False,
 'conf': False,
 'connect': False,
 'disconnect': False,
 'list': True}
18:31:40 vpn.py:123 DEBUG    [Tunnelblick] appinfo=None
18:31:40 workflow.py:2254 DEBUG    set last run version: 3.2.0
18:31:40 workflow.py:2103 DEBUG    ---------- finished in 0.046s ----------
[18:31:40.833] VPN Manager[Script Filter] {"items": [{"valid": false, "subtitle": "Use \"vpnconf\" to change the application", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"}, "title": "Application \"Tunnelblick\" is not installed"}]}
```

### Where is the application Tunnelblick installed?

/Applications/Tunnelblick.app

### What version of macOS are you using?

Catalina 10.15.4 (19E287)

### Can Alfred/Spotlight find Tunnelblick?

Yes

**Comment by deanishe** [comment]
I'm at a loss, I'm afraid. I have the same configuration, and it works fine here.

You could try running [this workflow](https://github.com/deanishe/alfred-fixum) to update the bundled version of the Alfred-Workflow library. Newer versions have some fixes for Catalina.

**Comment by DieterHolvoet** [comment]
Yeah, I have that workflow installed. I just tried and it has nothing to fix. I switched to https://github.com/phpfunk/alfred-tunnelblick, that one does work for me. Thanks for having a look though! Must be something with my setup, maybe a permissions problem or something.

**Comment by deanishe** [comment]
> I just tried and it has nothing to fix

Then you need to update that one first with `fixum workflow:update`.

> I switched to https://github.com/phpfunk/alfred-tunnelblick, that one does work for me

Might as well stick with that one, then, if you don't use Viscosity.

> I switched to https://github.com/phpfunk/alfred-tunnelblick, that one does work for me

If the workflow can't find the app, it's almost certainly a problem with the way it's calling Spotlight.

**Comment by DieterHolvoet** [comment]
Yeah, that's probably the reason. I recently disabled Spotlight indexing.

**Comment by deanishe** [comment]
Right. That would break the workflow. And Alfred. I think I can close this one.
