### ISSUE TITLE
Workflow alfred-viscosity slowing down macbook 12 on sierra 10.12.4 - more than 100% CPU ressources due to python

### ISSUE THREAD

**Issue by nx357** [deanishe/alfred-viscosity#2]
Hello,

I want to report you that your workflow is slowing down my computer since the upgrade to 10.12.4
When I looked at Activity monitor, it says that python has an impact of 90% (it can be more than 100%).
I am running alfred 3.3.1[806] on a macbook 12 retina with sierra 10.12.4 16E195.

Alfred-viscosity appears in python process : (see capture attached)

<img width="640" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/7515089/24548052/55ac1db0-1613-11e7-8cea-62bae2174124.png">

Attached is a sample of python.

[Sample of Python.txt](https://github.com/deanishe/alfred-viscosity/files/885358/Sample.of.Python.txt)

Hope it will help you to find out.

Regards

**Comment by deanishe** [comment]
Thanks for the info.

It's an [issue with Sierra and the Alfred-Workflow library](https://github.com/deanishe/alfred-workflow/issues/111).

I'm looking into a fix, but my Mac doesn't support Sierra.

**Comment by deanishe** [comment]
The issue should be fixed in [v2.0](https://github.com/deanishe/alfred-viscosity/releases/tag/v2.0).

**Comment by nx357** [comment]
Hi Dean,

Thank you. I will install it and let you know

Have a nice week end

Regards

—
Alex

**Comment by nx357** [comment]
Hi dean, everything is okay with your fix. No more high CPU usage.
