### ISSUE TITLE
Spaces in VPN connection name not handled

### ISSUE THREAD

**Issue by ryantrip** [deanishe/alfred-viscosity#3]
Hello,

It appears that spaces in the VPN connection name are not handled correctly. I tried adding quotations around the "%1" in Alfred, but that appears to break connect / disconnect feature completely. I have no Python skills unfortunately to assist, but maybe you can help me figure out a resolution. Thank you for this workflow!

**Comment by deanishe** [comment]
Thanks for finding that bug. I accidentally introduced it updating the workflow with Alfred 3 idioms.

[v2.0.1](https://github.com/deanishe/alfred-viscosity/releases/tag/v2.0.1) has fixed it.
